#!/bin/bash

button1_state=0  #connected on gpio pin 2
button2_state=0	 #connected on gpio pin 3
button3_state=0  #connected on gpio pin 4
button4_state=0  #connected on gpio pin 14
led_state=0	 #connected on gpio pin 26

#Checking if the pins are configured before 
if [ ! -d /sys/class/gpio/gpio2 ] ; then
	echo "2" >  /sys/class/gpio/export
	echo "in" >  /sys/class/gpio/gpio2/direction
fi

if [ ! -d /sys/class/gpio/gpio3 ] ; then
	echo "3" > /sys/class/gpio/export
	echo "in" > /sys/class/gpio/gpio3/direction
fi

if [ ! -d /sys/class/gpio/gpio4 ] ; then
	echo "4" >  /sys/class/gpio/export
	echo "in" >  /sys/class/gpio/gpio4/direction
fi

if [ ! -d /sys/class/gpio/gpio18 ] ; then
	echo "18" > /sys/class/gpio/export
	echo "in" >  /sys/class/gpio/gpio18/direction
fi

if [ ! -d /sys/class/gpio/gpio26 ] ; then
	echo "26" >  /sys/class/gpio/export
	echo "out" >  /sys/class/gpio/gpio26/direction
fi

while :
do
	
	if [ $(cat /sys/class/gpio/gpio2/value) -eq 1 ] || [ $(cat /sys/class/gpio/gpio3/value) -eq 1 ] || [ $(cat /sys/class/gpio/gpio4/value) -eq 1 ] || [ $(cat /sys/class/gpio/gpio18/value) -eq 1 ] ; then
	#TOGGLE BUTTON STATE
		if [ $button1_state -eq 0 ] 
		then
		button1_state=1
		sleep 0.3
		else
		button1_state=0
		sleep 0.3
		fi
	fi

	if [ $button1_state -eq 1 ] ; then
			echo "1" > /sys/class/gpio/gpio26/value
			else
			echo "0" > /sys/class/gpio/gpio26/value
	fi
done
